### ISSUE TITLE
Technical Milestones

### ISSUE THREAD

**Issue by rschragger** [rschragger/Activity_Arranger_Aide#2]
CLIENT
- [ ] Wireframes and user stories
- [ ] React setup
- [ ] Apollo setup - where we have queries and mutations
- [ ] Get CSS framework going
- [ ] 

SERVER
- [ ] Mongo DB Models
- [ ] JWT Authorisation - to level where auth middleware is done
